name: Awesome CI Workflow

on: [push, pull_request]

jobs:
  MainSequence:
    name: Code Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - name: requirements
        run: | 
          sudo apt -qq -y update
          sudo apt -qq install clang-tidy-10 clang-format-10
                    
  build:
    runs-on: ${{ matrix.os }}
    needs: [MainSequence]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - run: cmake -B ./build -S .
      - run: cmake --build build

    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macOS-latest]
    # steps:
    # - uses: actions/checkout@v2

    # - name: Create Build Environment
    #   run: cmake -E make_directory ${{runner.workspace}}/build

    # - name: Build
    #   shell: bash
    #   working-directory: ${{runner.workspace}}/build
    #   run: cmake $GITHUB_WORKSPACE && make

    # - name: Testing Operators
    #   working-directory: ${{runner.workspace}}/build/tests/operators
    #   shell: bash
    #   run: ctest

    # - name: Testing Operations
    #   working-directory: ${{runner.workspace}}/build/tests/operations
    #   shell: bash
    #   run: ctest
    
    - name: Running Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest
